package gui;

import javax.swing.JPanel;
import javax.swing.JTextArea;

public class IntroducirSentencias extends JPanel {
	/**
	 * Autogenerated serialVersionUID by JPanel
	 */
	private static final long serialVersionUID = -2277538189367154315L;

	/**
	 * Create the application.
	 */
	public IntroducirSentencias() {
		initialize();
	}

	/**
	 * Initialize the contents of the frame.
	 */
	private void initialize() {
		this.setBounds(100, 100, 450, 300);
		JTextArea input = new JTextArea();
		this.add(input);
	}

}
