package gui;

import java.awt.EventQueue;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JFrame;

public class LogIn extends JFrame{

	/**
	 * Autogenerated serialVersionUID for JFrame
	 */
	private static final long serialVersionUID = 8518395601546421684L;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					LogIn window = new LogIn();
					window.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the application.
	 */
	public LogIn() {
		initialize(this);
	}

	/**
	 * Initialize the contents of the frame.
	 */
	private void initialize(JFrame frame) {
		frame.setBounds(100, 100, 450, 300);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setLayout(new FlowLayout());
		
		JButton buttonAdm = new JButton("Admin LogIn");
		buttonAdm.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				JFrame nframe = new AdminWindow();
				nframe.setVisible(true);
				frame.dispose();
			}
		});
		
		frame.add(buttonAdm);
		
		JButton buttonEmp = new JButton("Empleado LogIn");
		buttonEmp.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				JFrame nframe = new EmpWindow();
				nframe.setVisible(true);
				frame.dispose();
			}
		});
		
		frame.add(buttonEmp);
	}

}
